skra = input("Sláðu inn nafn á skrá ")
nafnaskra = skra + ".txt"
txtfile = open(nafnaskra, 'w+')
lina = input("skrifaðu eitthvað ")
txtfile.write(lina + '\n')
txtfile.close()
txtfile = open(nafnaskra, 'a')
lina1 = input("Skrifaði firstu línuna ")
lina2 = input("Skrifaði seinni línuna ")
lina3 = input("Skrifaði þriðju línuna ")
txtfile.write(lina1 + '\n')
txtfile.write(lina2 + '\n')
txtfile.write(lina3 + '\n')
txtfile.close()
txtfile = open(nafnaskra, 'r')
txtfil = txtfile.read()
print (txtfil)
txtfile.close()
